[package]
name = "occulus-discord-bot"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonrpc-core = "18.0"
jsonrpc-derive = "18.0"
jsonrpc-tcp-server = "18.0"
log = "0.4.14"
rand = "0.8.4"
rust-embed = "6.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
serenity = "0.10"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1.26"
tracing-log = "0.1.2"
tracing-subscriber = "0.2"
